
local L = AceLibrary("AceLocale-2.2"):new("ItemHints")
L:RegisterTranslations("enUS", function() return {
  ["Activate/Suspend 'Item Hints'"] = true,
  ["Active"] = true,
  ["Add item to Custom"] = true,
  ["Add"] = true,
  ["Custom"] = true,
  ["Enable"] = true,
  ["Favorite"] = true,
  ["GearSet"] = true,
  ["Hide minimap icon"] = true,
  ["Item Hints"] = true,
  ["Manage Custom Hints"] = true,
  ["Remove item from Custom"] = true,
  ["Remove"] = true,
  ["Right-click for Options"] = true,
  ["Show Custom Hint"] = true,
  ["Show Favorite Hint (requires pfQuest)"] = true,
  ["Show GearSet Hint (requires ItemRack or Outfitter)"] = true,
  ["Show WishList Hint (requires AtlasLoot)"] = true,
  ["WishList"] = true,
  ["|cff00FFFFFavorite|r"] = true,
  ["|cffDC143CCustom|r"] = true,
  ["|cffFF69B4WishList|r"] = true,
  ["|cffFF8C00GearSets:|r %s"] = true,
  ["|cffFF8C00Hint: %s"] = true,
} end)

L:RegisterTranslations("zhCN", function() return {
  ["Activate/Suspend 'Item Hints'"] = "启动/停止 '物品提示'",
  ["Active"] = "启动",
  ["Add item to Custom"] = "自定义添加物品",
  ["Add"] = "添加",
  ["Custom"] = "自定义",
  ["Enable"] = "启用",
  ["Favorite"] = "收藏",
  ["GearSet"] = "套装装备",
  ["Hide minimap icon"] = "隐藏小地图图标",
  ["Item Hints"] = "物品提示",
  ["Manage Custom Hints"] = "管理自定义提示",
  ["Remove item from Custom"] = "从自定义删除物品",
  ["Remove"] = "删除",
  ["Right-click for Options"] = "右键设置",
  ["Show Custom Hint"] = "显示自定义提示",
  ["Show Favorite Hint (requires pfQuest)"] = "显示收藏提示(需要pfquest)",
  ["Show GearSet Hint (requires ItemRack or Outfitter)"] = "显示套装装备提示(需要ItemRack或Outfitter)",
  ["Show WishList Hint (requires AtlasLoot)"] = "显示白名单提示(需要AtlasLoot)",
  ["WishList"] = "白名单",
  ["|cff00FFFFFavorite|r"] = "|cff00FFFFPfquest收藏|r",
  ["|cffDC143CCustom|r"] = "|cffDC143C自定义|r",
  ["|cffFF69B4WishList|r"] = "|cffFF69B4Atlas收藏|r",
  ["|cffFF8C00GearSets:|r %s"] = "|cffFF8C00套装装备:|r %s",
  ["|cffFF8C00Hint: %s"] = "|cffFF8C00提示: %s",
} end)
